BYTE_ORDER = "little"

HEX_POSITIONS = {"PACKET_TYPE": (0, 1), "PACKET_VERSION": (2, 3), "ENERGY_USED": (4, 11), "TIME_DRIFT": (12, 19), "FLAGS": (20, 21)}
FLAG_POS = {"GEYSER_WARM": 0, "GEYSER_POWER": 1}

